/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function LidAndBaseSkeleton(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/models/lid-and-base/lid-and-base.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Mesh_0">
          <mesh
            name="Mesh_0_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0_1.geometry}
            material={materials.Material_color_base_outside}
          />
          <mesh
            name="Mesh_0_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0_2.geometry}
            material={materials.Material_color_base_inside}
          />
          <mesh
            name="Mesh_0_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0_3.geometry}
            material={materials.Material_side}
          />
        </group>
        <group name="Mesh_0001">
          <mesh
            name="Mesh_0001_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0001_1.geometry}
            material={materials.Material_color_lid_outside}
          />
          <mesh
            name="Mesh_0001_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0001_2.geometry}
            material={materials.Material_color_lid_inside}
          />
          <mesh
            name="Mesh_0001_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0001_3.geometry}
            material={materials.Material_side}
          />
          <mesh
            name="Mesh_0001_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0001_4.geometry}
            material={materials.finishing_gold_foil}
          />
          <mesh
            name="Mesh_0001_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0001_5.geometry}
            material={materials.finishing_spot_gloss}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/lid-and-base/lid-and-base.glb')
