/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 mailer-box.gltf 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { preloadTextures } from '../../lib/utils'

export function MailerBoxGltf (props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/assets/models/mailer/mailer-box.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    preloadTextures()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Armature001' rotation={[Math.PI, 0, Math.PI]}>
          <primitive object={nodes.Bone008} />
          <primitive object={nodes.neutral_bone} />
          <group name='material_print001'>
            <skinnedMesh
              name='material_print001_1'
              geometry={nodes.material_print001_1.geometry}
              material={materials.Material_color_outside}
              skeleton={nodes.material_print001_1.skeleton}
            />
            <skinnedMesh
              name='material_print001_2'
              geometry={nodes.material_print001_2.geometry}
              material={materials.Material_color_inside}
              skeleton={nodes.material_print001_2.skeleton}
            />
            <skinnedMesh
              name='material_print001_3'
              geometry={nodes.material_print001_3.geometry}
              material={materials.Material_side}
              skeleton={nodes.material_print001_3.skeleton}
            />
            <skinnedMesh
              name='material_print001_4'
              geometry={nodes.material_print001_4.geometry}
              material={materials.finishing_gold_foil}
              skeleton={nodes.material_print001_4.skeleton}
            />
            <skinnedMesh
              name='material_print001_5'
              geometry={nodes.material_print001_5.geometry}
              material={materials.finishing_spot_gloss}
              skeleton={nodes.material_print001_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/mailer/mailer-box.gltf')
