/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 output.glb --draco 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function TestTuckend (props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(
    '/assets/models/tuckend/test-tuckend.glb'
  )
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Armature' position={[0, -0.01, 0]} scale={0.073}>
          <primitive object={nodes.main} />
          <primitive object={nodes.neutral_bone} />
          <group name='Mesh_0004'>
            <skinnedMesh
              name='Mesh_0004_1'
              geometry={nodes.Mesh_0004_1.geometry}
              material={materials.Material_color_outside}
              skeleton={nodes.Mesh_0004_1.skeleton}
            />
            <skinnedMesh
              name='Mesh_0004_2'
              geometry={nodes.Mesh_0004_2.geometry}
              material={materials.Material_color_inside}
              skeleton={nodes.Mesh_0004_2.skeleton}
            />
            <skinnedMesh
              name='Mesh_0004_3'
              geometry={nodes.Mesh_0004_3.geometry}
              material={materials.Material_side}
              skeleton={nodes.Mesh_0004_3.skeleton}
            />
            <skinnedMesh
              name='Mesh_0004_4'
              geometry={nodes.Mesh_0004_4.geometry}
              material={materials.finishing_gold_foil}
              skeleton={nodes.Mesh_0004_4.skeleton}
            />
            <skinnedMesh
              name='Mesh_0004_5'
              geometry={nodes.Mesh_0004_5.geometry}
              material={materials.finishing_spot_gloss}
              skeleton={nodes.Mesh_0004_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload('/assets/models/tuckend/test-tuckend.glb')
