/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 tuckend.glb --transform 
Files: tuckend.glb [762.96KB] > C:\Users\Uzair\Documents\GitHub\Duncan-demo\public\assets\models\tuckend\tuckend-transformed.glb [95.07KB] (88%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model (props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/tuckend-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Armature' position={[0, -0.01, 0]} scale={0.073}>
          <primitive object={nodes.main} />
          <primitive object={nodes.neutral_bone} />
        </group>
        <group name='Mesh_0004' position={[0, -0.01, 0]} scale={0.073}>
          <skinnedMesh
            name='Mesh_0004_1'
            geometry={nodes.Mesh_0004_1.geometry}
            material={materials.Material_color_outside}
            skeleton={nodes.Mesh_0004_1.skeleton}
          />
          <skinnedMesh
            name='Mesh_0004_2'
            geometry={nodes.Mesh_0004_2.geometry}
            material={materials.Material_color_outside}
            skeleton={nodes.Mesh_0004_2.skeleton}
          />
          <skinnedMesh
            name='Mesh_0004_3'
            geometry={nodes.Mesh_0004_3.geometry}
            material={materials.Material_side}
            skeleton={nodes.Mesh_0004_3.skeleton}
          />
          <skinnedMesh
            name='Mesh_0004_4'
            geometry={nodes.Mesh_0004_4.geometry}
            material={materials.finishing_gold_foil}
            skeleton={nodes.Mesh_0004_4.skeleton}
          />
          <skinnedMesh
            name='Mesh_0004_5'
            geometry={nodes.Mesh_0004_5.geometry}
            material={materials.finishing_spot_gloss}
            skeleton={nodes.Mesh_0004_5.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tuckend-transformed.glb')
